"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";

const ASPECTS = [
  { value: "16:9", label: "Landscape 16:9" },
  { value: "9:16", label: "Portrait 9:16 (Pinterest)" },
  { value: "1:1", label: "Square 1:1" },
  { value: "3:4", label: "Portrait 3:4" },
  { value: "4:3", label: "Landscape 4:3" },
];

export default function AskmPage() {
  const router = useRouter();
  const [prompt, setPrompt] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [posting, setPosting] = useState(false);
  const [authorized, setAuthorized] = useState(false);
  const [aspectRatio, setAspectRatio] = useState("16:9");
  const [pinterestConnected, setPinterestConnected] = useState(false);
  const [boards, setBoards] = useState<any[]>([]);
  const [selectedBoard, setSelectedBoard] = useState("");

  useEffect(() => {
    if (!localStorage.getItem("baddie_user_email")) {
      router.replace("/");
    } else {
      setAuthorized(true);
      const token = localStorage.getItem("pinterest_token");
      if (token) {
        setPinterestConnected(true);
        const storedBoards = localStorage.getItem("pinterest_boards");
        if (storedBoards) {
          try {
            const parsed = JSON.parse(storedBoards);
            setBoards(parsed);
            if (parsed.length > 0) setSelectedBoard(parsed[0].id);
          } catch {}
        }
      }
    }
  }, [router]);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;
    setLoading(true);
    setImageUrl("");
    try {
      const res = await fetch("/api/generate-image", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: prompt.trim(), aspectRatio }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setImageUrl(`data:image/jpeg;base64,${data.image}`);
    } catch (err: any) {
      alert(err.message || "Failed to generate image");
    } finally {
      setLoading(false);
    }
  };

  const postToPinterest = async () => {
    const token = localStorage.getItem("pinterest_token");
    if (!token) return alert("Connect Pinterest first");

    if (!selectedBoard) return alert("Select a board");

    setPosting(true);
    try {
      // Convert base64 to blob, upload to a temp service, then post
      const res = await fetch("/api/pinterest/pins", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          token,
          title: prompt,
          description: `${prompt} — Generated by CHATPATTIE BADDIE AI`,
          board_id: selectedBoard,
          image_url: imageUrl,
        }),
      });
      const data = await res.json();
      if (data.id) {
        alert("✅ Posted to Pinterest!");
      } else {
        alert("Error: " + (data.error || "Unknown"));
      }
    } catch {
      alert("Failed to post to Pinterest");
    } finally {
      setPosting(false);
    }
  };

  if (!authorized) return null;

  return (
    <div className="p-4 max-w-lg mx-auto">
      <div className="text-center mb-6">
        <span className="text-4xl">🎨</span>
        <h1 className="text-2xl font-bold text-gray-900 mt-2">AskM — AI Image Generator</h1>
        <p className="text-sm text-gray-500 mt-1">Generate images with AI, then post to Pinterest</p>
      </div>

      <form onSubmit={handleGenerate} className="flex flex-col gap-3 mb-6">
        <div className="flex gap-2">
          <input
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="e.g. a cat in space with rainbow stars"
            className="flex-1 px-4 py-3 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-purple-200 focus:border-purple-400"
          />
          <button
            type="submit"
            disabled={loading || !prompt.trim()}
            className="px-5 py-3 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-xl text-sm font-medium hover:opacity-90 disabled:opacity-50 transition-all"
          >
            {loading ? "..." : "Create"}
          </button>
        </div>

        <select
          value={aspectRatio}
          onChange={(e) => setAspectRatio(e.target.value)}
          className="px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white focus:outline-none focus:ring-2 focus:ring-purple-200"
        >
          {ASPECTS.map((a) => (
            <option key={a.value} value={a.value}>{a.label}</option>
          ))}
        </select>
      </form>

      <div className="w-full my-4">
        <ins className="adsbygoogle" style={{ display: "inline-block", width: "728px", height: "90px" }} data-ad-client="ca-pub-4486222454241909" data-ad-slot="9286475415" />
      </div>

      {imageUrl && (
        <div className="bg-gray-50 rounded-2xl p-4 border border-gray-100">
          <div className="relative">
            <img
              src={imageUrl}
              alt={prompt}
              className="w-full rounded-xl"
              style={{ aspectRatio: aspectRatio === "9:16" ? "9/16" : aspectRatio === "1:1" ? "1/1" : aspectRatio === "3:4" ? "3/4" : aspectRatio === "4:3" ? "4/3" : "16/9" }}
            />
          </div>
          <p className="text-xs text-gray-400 text-center mt-3">"{prompt}"</p>

          <div className="flex gap-2 mt-3">
            <a
              href={imageUrl}
              download={`askm-${Date.now()}.jpg`}
              className="flex-1 py-2.5 bg-gray-900 text-white rounded-full text-sm font-medium text-center hover:bg-gray-800 transition-all"
            >
              Download
            </a>

            {pinterestConnected ? (
              <div className="flex flex-col gap-2 flex-1">
                {boards.length > 0 && (
                  <select
                    value={selectedBoard}
                    onChange={(e) => setSelectedBoard(e.target.value)}
                    className="px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white text-gray-700"
                  >
                    {boards.map((b: any) => (
                      <option key={b.id} value={b.id}>{b.name}</option>
                    ))}
                  </select>
                )}
                <button
                  onClick={postToPinterest}
                  disabled={posting}
                  className="w-full py-2.5 bg-red-600 text-white rounded-full text-sm font-medium hover:bg-red-700 transition-all disabled:opacity-50"
                >
                  {posting ? "Posting..." : "📌 Post to Pinterest"}
                </button>
              </div>
            ) : (
              <a
                href="/pinterest"
                className="flex-1 py-2.5 bg-gray-200 text-gray-600 rounded-full text-sm font-medium text-center hover:bg-gray-300 transition-all"
              >
                🔗 Connect Pinterest
              </a>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
