import { neon } from "@neondatabase/serverless";
import { config } from "dotenv";
config({ path: ".env.local" });
const sql = neon(process.env.DATABASE_URL);
const tables = await sql`SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'`;
console.log("Tables:", tables.map(t => t.table_name).join(", "));
const vc = await sql`SELECT COUNT(*) as c FROM vents`;
console.log("Total vents:", vc[0].c);
const dc = await sql`SELECT COUNT(*) as c FROM daily_usage`;
console.log("Total daily_usage:", dc[0].c);
const sc = await sql`SELECT COUNT(*) as c FROM subscriptions`;
console.log("Total subscriptions:", sc[0].c);
